[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "python3 -m playwright install chromium"
]

[start]
cmd = "python3 main.py"
